server:
  port: 8088
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: jdbc:mysql://101.132.138.14:3306/whole_stack_demo
    username: DRT
    password: DRT1951725

    driver-class-name: com.mysql.cj.jdbc.Driver
    #for swagger
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# control the swagger is closed or not
swagger:
  enabled: true

mybatis:
  mapper-locations: classpath:/mapper/*.xml
