server:
  port: 8088
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: jdbc:mysql://101.132.138.14:3306/whole_stack_demo
    username: DRT
    password: DRT1951725

    driver-class-name: com.mysql.cj.jdbc.Driver
    #for swagger
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# control the swagger is closed or not
swagger:
  enabled: true

mybatis:
  mapper-locations: classpath:/mapper/*.xml


# Sa-Token??
sa-token:
  # token?? (????cookie??)  ???????:
  token-name: test-satoken
  # token??????s ????2??, -1??????
  timeout: 1200000
  # token????? (???????????token??) ??: ?
  activity-timeout: 1200000
  # ???????????? (?true???????, ?false?????????)
  is-concurrent: true
  # ?????????????????token (?true?????????token, ?false?????????token)
  is-share: false
  # token??
  token-style: random-128
  # ???cookie???token
  is-read-cookie: true
  # ?????????token
  is-read-body: true
  # ???head???token
  is-read-head: true
  # ????????
  is-log: true
  # ??url
  interceptUrlList:
#    - /**
  #   - /test/**
     - /user/**
  # ??url
  openUrlList:
#    - /**
#   - /test/doLogin
#   - /test/get
   - /user/test
   - /user/doLogin
